# Generated by Django 5.1.3 on 2026-01-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('urn', models.IntegerField(help_text='Unique identifier for each school', primary_key=True, serialize=False, unique=True)),
                ('establishment_name', models.CharField(help_text='Name of the school establishment', max_length=255)),
                ('local_authority', models.CharField(help_text='Local authority name (e.g., Camden, City of London)', max_length=255)),
                ('establishment_status', models.CharField(help_text='Status of the establishment', max_length=255)),
            ],
            options={
                'ordering': ['establishment_name'],
                'indexes': [models.Index(fields=['urn'], name='schools_sch_urn_3cf734_idx'), models.Index(fields=['local_authority'], name='schools_sch_local_a_b4aaaf_idx'), models.Index(fields=['establishment_status'], name='schools_sch_establi_a9768e_idx')],
            },
        ),
    ]
