# Generated by Django 5.1.3 on 2026-01-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='process',
            field=models.CharField(blank=True, help_text='Process information for the school', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='JSON data related to the school')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this data was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this data was last updated')),
                ('school', models.ForeignKey(help_text='Related school', on_delete=django.db.models.deletion.CASCADE, related_name='school_data', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='schools_sch_school__aac1b8_idx')],
            },
        ),
    ]
