# Generated by Django 5.1.3 on 2026-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_process_schooldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, help_text='School website URL', max_length=500, null=True),
        ),
    ]
