# Generated by Django 5.1.3 on 2026-01-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='process',
            field=models.BooleanField(default=False, help_text='Process status for the school'),
        ),
    ]
