# Generated by Django 5.1.3 on 2026-01-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='second_scraper',
            field=models.BooleanField(default=False, help_text='Second scraper status for the school'),
        ),
    ]
