# Generated by Django 4.2.27 on 2026-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_add_second_scraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='third_scraper',
            field=models.BooleanField(default=False, help_text='Second scraper status for the school'),
        ),
    ]
